Repository TeamHARA/HARA_AOS, pull requests merged in 2023-01, with the labels that each got.

#10 Feature/#6 together view
  app/src/main/java/com/android/hara/presentation/home/fragment/CategoryAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/TogetherFragment.kt
  app/src/main/res/drawable/selector_rectangle_white_blue.xml
  app/src/main/res/drawable/selector_rectangle_white_orange3.xml
  app/src/main/res/drawable/selector_text_blue_white.xml
  app/src/main/res/drawable/shape_rectangle_blue1_fill_8.xml
  app/src/main/res/drawable/shape_rectangle_blue1_stroke_1_8.xml
  app/src/main/res/drawable/shape_rectangle_blue2_stroke_1_8.xml
  app/src/main/res/drawable/shape_rectangle_gray4_stroke_1_8.xml
  app/src/main/res/drawable/shape_rectangle_orange2_stroke_1_8.xml
  app/src/main/res/drawable/shape_rectangle_orange3_fill_8.xml
  app/src/main/res/layout/fragment_together.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_worry.xml
  app/src/main/res/values/strings.xml
Labels: 유진🐱

#12 [Fix] Rename mipmap files / Delete mipmap files
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/release/hara_launcher-playstore.png
  app/src/release/res/drawable/hara_launcher_foreground.xml
  app/src/release/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/release/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/release/res/mipmap-hdpi/ic_launcher.png
  app/src/release/res/mipmap-hdpi/ic_launcher_round.png
  app/src/release/res/mipmap-mdpi/ic_launcher.png
  app/src/release/res/mipmap-mdpi/ic_launcher_round.png
  app/src/release/res/mipmap-xhdpi/ic_launcher.png
  app/src/release/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/release/res/mipmap-xxhdpi/ic_launcher.png
  app/src/release/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/release/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/release/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/release/res/values/hara_launcher_background.xml
Labels: 준우🦦

#13 Feature/#7 storage
  app/src/main/res/drawable/selector_storage_check_btn.xml
  app/src/main/res/drawable/shape_rectangle_blue3_stroke_1_30.xml
  app/src/main/res/drawable/shape_rectangle_orange2_stroke_1_4.xml
  app/src/main/res/drawable/shape_rectanle_orange1_fill_4.xml
  app/src/main/res/drawable/shape_stroke_blue3.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_storage.xml
  app/src/main/res/values/strings.xml
Labels: 수현🐰

#16 Feature/#8 상세보기 화면 구성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/presentation/custom/DecisionDialog.kt
  app/src/main/java/com/android/hara/presentation/custom/model/DialogData.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailActivity.kt
  app/src/main/java/com/android/hara/presentation/util/ViewExtension.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/selector_detail_checkbox.xml
  app/src/main/res/drawable/shape_rectangle_blue3_fill_8.xml
  app/src/main/res/drawable/shape_rectangle_gray4_fill_8.xml
  app/src/main/res/drawable/shape_rectangle_white_fill_8.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/dialog_decision.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 준우🦦

#21 Feature/#14 1초만에 고민해결하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/presentation/cardgame/CardGameActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/FinalDecideActivity.kt
  app/src/main/java/com/android/hara/presentation/onesec/OneSecActivity.kt
  app/src/main/java/com/android/hara/presentation/onesec/adapter/OneSecAdapter.kt
  app/src/main/java/com/android/hara/presentation/onesec/model/WorryData.kt
  app/src/main/java/com/android/hara/presentation/onesec/viewmodel/OneSecViewModel.kt
  app/src/main/java/com/android/hara/presentation/util/GlobalDiffCallBack.kt
  app/src/main/res/drawable/img_card_result.xml
  app/src/main/res/drawable/img_game.xml
  app/src/main/res/drawable/img_one_sec.xml
  app/src/main/res/font/cafe24_ssurround.otf
  app/src/main/res/font/font_family.xml
  app/src/main/res/layout/activity_card_game.xml
  app/src/main/res/layout/activity_one_sec.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_last_worry.xml
  app/src/main/res/values/strings.xml
Labels: 준우🦦

#26 Feature/#25 힐트 적용 및 서버통신환경 구축
  app/src/main/java/com/android/hara/data/datasource/HARAService.kt
  app/src/main/java/com/android/hara/data/datasource/HaraService.kt
  app/src/main/java/com/android/hara/data/datasource/ReqresApi.kt
  app/src/main/java/com/android/hara/data/model/request/RequestReqresUserDTO.kt
  app/src/main/java/com/android/hara/data/model/request/RequestVoteDTO.kt
  app/src/main/java/com/android/hara/data/model/response/ReqresUserDTO.kt
  app/src/main/java/com/android/hara/data/model/response/ResponseReqresListDTO.kt
  app/src/main/java/com/android/hara/data/model/response/ResponseVoteDTO.kt
  app/src/main/java/com/android/hara/data/repository/HARARepositoryImpl.kt
  app/src/main/java/com/android/hara/data/repository/HaraRepositoryImpl.kt
  app/src/main/java/com/android/hara/data/repository/ReqresRepositoryImpl.kt
  app/src/main/java/com/android/hara/data/util/Constant.kt
  app/src/main/java/com/android/hara/di/DataSourceModule.kt
  app/src/main/java/com/android/hara/di/RepositroyModule.kt
  app/src/main/java/com/android/hara/di/ServiceModule.kt
  app/src/main/java/com/android/hara/domain/repository/HARARepository.kt
  app/src/main/java/com/android/hara/domain/repository/HaraRepository.kt
  app/src/main/java/com/android/hara/domain/repository/ReqresRepository.kt
  app/src/main/java/com/android/hara/presentation/custom/DecisionDialog.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/FinalDecideActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/FinalResolveActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/viewmodel/DecideViewModel.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/StorageFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/StorageSelfFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/StorageTogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/hara/presentation/onesec/OneSecActivity.kt
  app/src/main/java/com/android/hara/presentation/onesec/viewmodel/OneSecViewModel.kt
  app/src/main/java/com/android/hara/presentation/setting/SettingActivity.kt
Labels: 준우🦦

#27 Feature/#24 detail activity 옵션/버튼 로직
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/presentation/detail/DetailActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/viewmodel/DetailViewModel.kt
  app/src/main/res/drawable/shape_rectangle_gray3_fill_8.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_final_option.xml
  app/src/main/res/layout/layout_detail_option.xml
Labels: 수현🐰

#31 Feature/#22 카테고리 피커/바텀시트, 홈화면 바텀내비게이션, 상단 앱바
  app/src/main/java/com/android/hara/presentation/base/BindingDraggableBottomSheet.kt
  app/src/main/java/com/android/hara/presentation/base/BindingNotDraggableBottomSheet.kt
  app/src/main/java/com/android/hara/presentation/custom/PickerBottomSheetDialog.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/java/com/android/hara/presentation/util/HARAobjcet.kt
  app/src/main/res/drawable/selector_picker_text.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_bottomsheet_picker.xml
  app/src/main/res/menu/top_community_menu.xml
  app/src/main/res/menu/top_stroage_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 준우🦦

#34 Feature/#33 home category btn logic
  app/src/main/java/com/android/hara/presentation/home/fragment/together/CategoryAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/SimpleModel.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/res/layout/fragment_together.xml
  app/src/main/res/layout/item_category.xml
Labels: 유진🐱

#35 Feature/#28 홈 fragment : 글 목록 recycler view 구현
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/StorageAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/StorageFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/PostAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/model/TogetherPostData.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/fragment_together.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/item_storage.xml
  app/src/main/res/layout/item_worry.xml
  app/src/main/res/layout/layout_post_option.xml
Labels: 수현🐰

#41 Feature/#40 onesec server
  app/src/main/java/com/android/hara/data/datasource/HARAService.kt
  app/src/main/java/com/android/hara/data/model/response/OnesecResDto.kt
  app/src/main/java/com/android/hara/data/repository/HARARepositoryImpl.kt
  app/src/main/java/com/android/hara/domain/repository/HARARepository.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/with/StorageWithViewModel.kt
  app/src/main/java/com/android/hara/presentation/onesec/OneSecActivity.kt
  app/src/main/java/com/android/hara/presentation/onesec/viewmodel/OneSecViewModel.kt
  app/src/main/res/drawable/selector_rectangle_white_orange1_stroke_orange3.xml
  app/src/main/res/drawable/selector_text_gray2_orange3.xml
  app/src/main/res/drawable/shape_rectangle_orange1_fill_orange3_stroke_1_30.xml
  app/src/main/res/drawable/shape_rectangle_orange3_stroke_1_30.xml
  app/src/main/res/layout/activity_one_sec.xml
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#43 Feature/#42 [FEAT] 보관함 고민목록 조회 GET
  app/src/main/java/com/android/hara/data/datasource/HARAService.kt
  app/src/main/java/com/android/hara/data/model/response/RandomListResDto.kt
  app/src/main/java/com/android/hara/data/repository/HARARepositoryImpl.kt
  app/src/main/java/com/android/hara/domain/repository/HARARepository.kt
  app/src/main/java/com/android/hara/presentation/onesec/OneSecActivity.kt
  app/src/main/java/com/android/hara/presentation/onesec/adapter/OneSecAdapter.kt
  app/src/main/java/com/android/hara/presentation/onesec/model/WorryData.kt
  app/src/main/java/com/android/hara/presentation/onesec/viewmodel/OneSecViewModel.kt
  app/src/main/res/layout/item_last_worry.xml
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#46 Feature/#44 최종 결정 PATCH 통신 준비 및 상세화면 뷰 분리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/data/datasource/HARAService.kt
  app/src/main/java/com/android/hara/data/model/request/DecideAloneReqDto.kt
  app/src/main/java/com/android/hara/data/model/request/DecideWithReqDto.kt
  app/src/main/java/com/android/hara/data/model/response/DecisionResDto.kt
  app/src/main/java/com/android/hara/data/model/response/WorryListResDto.kt
  app/src/main/java/com/android/hara/data/repository/HARARepositoryImpl.kt
  app/src/main/java/com/android/hara/domain/repository/HARARepository.kt
  app/src/main/java/com/android/hara/presentation/decision/DecideViewModel.kt
  app/src/main/java/com/android/hara/presentation/decision/FinalDecideActivity.kt
  app/src/main/java/com/android/hara/presentation/decision/FinalResolveActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailActivity.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/res/drawable/selector_rectangle_white_orange1_stroke_orange3.xml
  app/src/main/res/drawable/selector_text_gray3_orange3.xml
  app/src/main/res/drawable/shape_rectangle_gray4_stroke_1_30.xml
  app/src/main/res/layout/activity_detail_alone.xml
  app/src/main/res/layout/activity_detail_with.xml
  app/src/main/res/layout/activity_final_decide.xml
  app/src/main/res/layout/activity_final_resolve.xml
  app/src/main/res/layout/activity_one_sec.xml
  app/src/main/res/layout/item_final_decide_img.xml
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#48 Feature/#37 홈화면 : GET/POST 서버 통신, 옵션/버튼 스타일 변경 로직
  app/src/main/java/com/android/hara/data/datasource/HARAService.kt
  app/src/main/java/com/android/hara/data/model/request/VoteReqDto.kt
  app/src/main/java/com/android/hara/data/model/response/AllPostResDto.kt
  app/src/main/java/com/android/hara/data/model/response/VoteResDto.kt
  app/src/main/java/com/android/hara/data/repository/HARARepositoryImpl.kt
  app/src/main/java/com/android/hara/domain/repository/HARARepository.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/CategoryAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/PostAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/hara/presentation/util/BindingConversion.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/layout_post_option.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 수현 🐰

#50 Feature/#45 게시글 생성 통신 / 기타 수정/이슈 반영
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/data/datasource/HARAService.kt
  app/src/main/java/com/android/hara/data/datasource/ReqresApi.kt
  app/src/main/java/com/android/hara/data/model/request/PostWorryOptionDto.kt
  app/src/main/java/com/android/hara/data/model/request/RequestReqresUserDTO.kt
  app/src/main/java/com/android/hara/data/model/request/WorryAloneRequestDto.kt
  app/src/main/java/com/android/hara/data/model/request/WorryWithRequestDto.kt
  app/src/main/java/com/android/hara/data/model/response/ReqresUserDTO.kt
  app/src/main/java/com/android/hara/data/model/response/ResponseReqresListDTO.kt
  app/src/main/java/com/android/hara/data/model/response/WorryAloneResponseDto.kt
  app/src/main/java/com/android/hara/data/model/response/WorryWithResponseDto.kt
  app/src/main/java/com/android/hara/data/repository/HARARepositoryImpl.kt
  app/src/main/java/com/android/hara/data/repository/ReqresRepositoryImpl.kt
  app/src/main/java/com/android/hara/di/DataSourceModule.kt
  app/src/main/java/com/android/hara/di/RepositroyModule.kt
  app/src/main/java/com/android/hara/di/ServiceModule.kt
  app/src/main/java/com/android/hara/domain/repository/HARARepository.kt
  app/src/main/java/com/android/hara/domain/repository/ReqresRepository.kt
  app/src/main/java/com/android/hara/presentation/custom/DecisionDialog.kt
  app/src/main/java/com/android/hara/presentation/custom/PickerBottomSheetDialog.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/CategoryAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/viewmodel/TogetherFragmentViewModel.kt
  app/src/main/java/com/android/hara/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/hara/presentation/util/HARAobjcet.kt
  app/src/main/java/com/android/hara/presentation/write/WriteActivity.kt
  app/src/main/java/com/android/hara/presentation/write/WriteViewModel.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/category/CategoryFregViewModel.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/category/WriteCategoryFragment.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/how/HowFragViewModel.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/how/WriteHowFragment.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/option/OptionFragViewModel.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/option/WriteOptionFragment.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/proscons/ProsconsFragViewModel.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/proscons/WriteProsconsFragment.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/what/WhatFragViewModel.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/what/WriteWhatFragment.kt
  app/src/main/res/drawable/selector_rectangle_blue3_blue1.xml
  app/src/main/res/drawable/shape_rectangle_white_blue3_stroke_1_1000.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_bottomsheet_picker.xml
  app/src/main/res/layout/fragment_together.xml
  app/src/main/res/layout/fragment_write_category.xml
  app/src/main/res/layout/fragment_write_how.xml
  app/src/main/res/layout/fragment_write_option.xml
  app/src/main/res/layout/fragment_write_proscons.xml
  app/src/main/res/layout/fragment_write_what.xml
  app/src/main/res/layout/item_write_option.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/write_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🦦 준우 🦦, ✨ FEAT ✨

#52 Feature/#51 검색뷰 완성 / 기타 스크롤 조정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/presentation/custom/PickerBottomSheetDialog.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/adapter/CategoryAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/adapter/PostAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/model/SimpleModel.kt
  app/src/main/java/com/android/hara/presentation/search/SearchActivity.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/category/WriteCategoryFragment.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🦦 준우 🦦, ✏️ UI ✏️

#55 [FEAT] 최종결정 이미지 & 문자열 처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/data/model/request/DecideAloneReqDto.kt
  app/src/main/java/com/android/hara/data/model/request/DecideWithReqDto.kt
  app/src/main/java/com/android/hara/data/model/response/WorryListResDto.kt
  app/src/main/java/com/android/hara/presentation/decision/DecideViewModel.kt
  app/src/main/java/com/android/hara/presentation/decision/FinalResolveActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/decision/DecideViewModel.kt
  app/src/main/java/com/android/hara/presentation/detail/decision/FinalDecideActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/decision/FinalResolveActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/model/DecideData.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/java/com/android/hara/presentation/util/BindingConversion.kt
  app/src/main/res/drawable/background.xml
  app/src/main/res/drawable/img_decide_text_result.xml
  app/src/main/res/layout/activity_final_decide.xml
  app/src/main/res/layout/activity_final_resolve.xml
  app/src/main/res/layout/activity_one_sec.xml
  app/src/main/res/layout/item_final_decide_img.xml
  app/src/main/res/layout/item_final_option.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_storage.xml
  app/src/main/res/values/dimens.xml
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#57 Feature/#53 상세화면 서버통신 / 세부반영 사항
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/data/datasource/HARAService.kt
  app/src/main/java/com/android/hara/data/model/response/DetailAloneResDto.kt
  app/src/main/java/com/android/hara/data/model/response/DetailWithResDto.kt
  app/src/main/java/com/android/hara/data/repository/HARARepositoryImpl.kt
  app/src/main/java/com/android/hara/domain/repository/HARARepository.kt
  app/src/main/java/com/android/hara/presentation/custom/EditBottomSheetDialog.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailAloneActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailWithActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/adapter/CommentAdapter.kt
  app/src/main/java/com/android/hara/presentation/detail/viewmodel/DetailAloneViewModel.kt
  app/src/main/java/com/android/hara/presentation/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/android/hara/presentation/detail/viewmodel/DetailWithViewModel.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/StorageAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/alone/StorageAloneFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/with/StorageWithFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/adapter/PostAdapter.kt
  app/src/main/res/drawable/ic_delete_post.xml
  app/src/main/res/drawable/shape_rectangle_grey2_12.xml
  app/src/main/res/layout/activity_detail_alone.xml
  app/src/main/res/layout/activity_detail_with.xml
  app/src/main/res/layout/fragment_bottomsheet_eidt_menu.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/layout_detail_option.xml
  app/src/main/res/values/strings.xml
Labels: 🦦 준우 🦦, ✨ FEAT ✨

#59 결정 완료 > 보관함 화면 전환
  app/src/main/java/com/android/hara/data/model/response/DetailAloneResDto.kt
  app/src/main/java/com/android/hara/presentation/detail/decision/FinalResolveActivity.kt
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/res/layout/activity_final_resolve.xml
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#61 Feature/#60 1초 해결 지난 고민 클릭 로직
  app/src/main/java/com/android/hara/presentation/onesec/OneSecActivity.kt
  app/src/main/java/com/android/hara/presentation/onesec/adapter/OneSecAdapter.kt
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#64 Feature/#58 스플래시 액티비티 / 세부 디테일
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/hara/SplashActivity.kt
  app/src/main/java/com/android/hara/presentation/custom/DecisionDialog.kt
  app/src/main/java/com/android/hara/presentation/custom/PickerBottomSheetDialog.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/adapter/PostAdapter.kt
  app/src/main/java/com/android/hara/presentation/util/BindingConversion.kt
  app/src/main/java/com/android/hara/presentation/util/GlobalFalseDiff.kt
  app/src/main/java/com/android/hara/presentation/write/fragment/option/adapter/WriteOptionAdapter.kt
  app/src/main/res/drawable/ic_splashlogo.xml
  app/src/main/res/layout/activity_detail_with.xml
  app/src/main/res/layout/activity_one_sec.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🦦 준우 🦦, ✨ FEAT ✨

#65 [Fix] 네비게이션 그래프 StartDestination 변경
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
Labels: 🐱 유진 🐱

#66 Feature/#49 홈 투표율, 버튼, 상세화면 이동 로직
  app/build.gradle
  app/src/main/java/com/android/hara/data/model/response/AllPostResDto.kt
  app/src/main/java/com/android/hara/data/model/response/DetailWithResDto.kt
  app/src/main/java/com/android/hara/data/model/response/VoteResDto.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailAloneActivity.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailWithActivity.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/StorageFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/storage/with/StorageWithFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/DetailData.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/adapter/PostAdapter.kt
  app/src/main/java/com/android/hara/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/hara/presentation/util/BindingConversion.kt
  app/src/main/res/drawable/shape_rectangle_blue1_stroke_1_8.xml
  app/src/main/res/drawable/shape_rectangle_gray4_stroke_1_8.xml
  app/src/main/res/layout/activity_detail_alone.xml
  app/src/main/res/layout/activity_detail_with.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/layout_detail_option.xml
  app/src/main/res/layout/layout_post_option.xml
Labels: 🐰 수현 🐰

#68 Feature/#67 final logic connect
  app/src/main/java/com/android/hara/presentation/home/HomeActivity.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/TogetherFragment.kt
  app/src/main/java/com/android/hara/presentation/home/fragment/together/adapter/PostAdapter.kt
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#70 Feature/#49 상세화면 옵션 뷰 수정
  app/src/main/java/com/android/hara/data/model/response/DetailAloneResDto.kt
  app/src/main/java/com/android/hara/data/model/response/DetailWithResDto.kt
  app/src/main/java/com/android/hara/presentation/detail/DetailWithActivity.kt
  app/src/main/res/layout/layout_detail_option.xml
Labels: 🐰 수현 🐰

#74 Feature/#71 함께고민 최종결정 patch 로직 추가
  app/src/main/java/com/android/hara/presentation/detail/DetailWithActivity.kt
  app/src/main/java/com/android/hara/presentation/util/BindingConversion.kt
Labels: 🐱 유진 🐱, ✨ FEAT ✨

#75 [Feat] 혼자고민 뷰 및 patch 통신 로직
  app/src/main/java/com/android/hara/presentation/detail/DetailAloneActivity.kt
Labels: 🐱 유진 🐱, ✨ FEAT ✨
